before_install:
- openssl aes-256-cbc -K $encrypted_d51026dfa49b_key -iv $encrypted_d51026dfa49b_iv
  -in cits-3200-abc14d0972cf.json.enc -out cits-3200-abc14d0972cf.json -d
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: cits-3200-abc14d0972cf.json
  project: cits-3200
